# .github/workflows/schema-export.yml
name: Export DB Schema

on:
  workflow_dispatch:   # ← 手動実行を有効化
    inputs:
      branch:
        description: "Run on branch"
        required: false
        default: "main"

jobs:
  export-schema:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch || 'main' }}

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install PostgreSQL client (psql)
        run: |
          sudo apt-get update
          sudo apt-get install -y postgresql-client dos2unix

      - name: Prep output dir & normalize SQL newlines
        run: |
          mkdir -p table-info
          dos2unix table-info/export-tableSchema.sql

      - name: Export CSVs with psql
        env:
          PGURL: ${{ secrets.PGURL }}
        run: |
          # 冗長ログで実行（行エコー & 詳細エラー）
          psql "$PGURL" -v ON_ERROR_STOP=1 -v VERBOSITY=verbose -a -f table-info/export-tableSchema.sql

      - name: Generate SCHEMA.md
        env:
          PGURL: ${{ secrets.PGURL }}
        run: npm run schema:md

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: table-schema
          path: |
            table-info/*.csv
            table-info/SCHEMA.md